language: rust

cache: cargo

rust:
  - stable

before_script:
- rustup component add rustfmt
- rustup component add clippy

script: |
  cargo fmt --all -- --check &&
  cargo clippy &&
  cargo build &&
  cargo test