name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install cbindgen
        run: cargo install cbindgen
      - name: Build
        run: make build-pkg
      - name: Run tests
        run: cargo test --verbose --workspace
