name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # - name: Install cbindgen
      #   run: cargo install cbindgen
      # - name: Install cargo wasi
      #   run: cargo install cargo-wasi
      # - name: Build wasm
      #   run: make build-wasm-pkg
      - name: Build lib
        run: make build-grpc-pkg
      - name: Build core
        run: make build-core-pkg
      - name: Run tests
        run: cargo test --verbose --workspace
