name: Clippy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo make install-deps
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
