[package]
name = "ain-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
env_logger = "0.9"
lazy_static = "1.4"
log = "0.4"

[build-dependencies]
cxx-gen = "0.7"
proc-macro2 = "1.0"
